<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [2]:
#python list
super_names= ["Black Widow", "Iron Man", "Doctor Strange"]
real_names= ["Natasha", "Tony", "Stephen"]

In [9]:
#numpy array
import numpy as np
np_super_names= np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names= np.array(["Natasha", "Tony", "Stephen"])
#must put np.array before ()

In [3]:
#dictionary
superhero_info= {
    "Natasha": "Black Widow",
    "Tony": "Iron Man",
    "Stephen": "Doctor Strange"
}
#"Natasha", "Tony" "Stephen" KEYS
#"Black Widow", "Iron Man", "Doctor Strange" VALUES
#see2.3 1.3

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [13]:
#python is 0 indexed language, starts counting at 0 (first item is 0)
real_names[0]

'Natasha'

In [14]:
#negative index counts from the back of list
super_names[-1]

'Doctor Strange'

In [18]:
np_super_names[-1]

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [15]:
superhero_info["Tony"]

'Iron Man'

In [16]:
superhero_info.keys() #what comes before :

dict_keys(['Natasha', 'Tony', 'Stephen'])

In [17]:
superhero_info.values() #what comes after :

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [19]:
#use 2 lists to store real and superhero names -> 2D list or array
py_superhero_info= [['Natasha', 'Black Widow'],
                    ['Tony', 'Iron Man'],
                    ['Stephen', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [4]:
py_list_2d= [[1,"A"],[2, "B"], [3,"C"], [4, "D"]]
np_array_2d= np.array(py_list_2d) #reuses python list to create new numpy array

#len() function to identify no of elements in lists/arrays
len(py_list_2d)

4

In [21]:
len(np_array_2d)

4

In [6]:
import numpy as np
np_array_2d.shape #shape is not a function () not required
                #displays (no of elements, no of elements in each dimension)

(4, 2)

In [8]:
py_list_2d[-1]

[4, 'D']

## 2.2 Arrays are fussy about type

In [10]:
py_list= [1,1.5,'A'] #list
np_array= np.array(py_list) #array

In [11]:
py_list

[1, 1.5, 'A']

In [12]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [13]:
py_list= [1,2,3,4,5]
np_array= np.array(py_list) #reuses python list to create new numpy array

In [16]:
#list
py_list +10 #will not work

TypeError: can only concatenate list (not "int") to list

In [17]:
#array
np_array +10 #works

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [18]:
py_list_1= [1,2,3,4,5]
py_list_2= [10,20,30,40,50]

np_array_1= np.array(py_list_1)
np_array_2= np.array(py_list_2)

In [23]:
py_list_1 + py_list_2
#shows all elements from list 1 and 2
#list grows

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [22]:
np_array_1 + np_array_2
#adds up list 1 + 2 elements together as per index (e.g. 1+10,2+20)

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [24]:
py_list= [1,2,3,4,5]
np_array= np.array(py_list)

In [26]:
py_list*2
#list grows

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [27]:
np_array*2
#multiplies elements by the number

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [28]:
py_list= [1,2,3,4,5]
np_array= np.array(py_list)

In [29]:
py_list**2 #wont work

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [30]:
np_array**2 #squares elements

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [31]:
py_list= [1,2,3,4,5]
np_array= np.array(py_list)

In [32]:
#lists

In [37]:
py_list== 3 #true/false, only tells if this number is in the list, not a question

False

In [36]:
py_list>3 #wont work

TypeError: '>' not supported between instances of 'list' and 'int'

In [38]:
#arrays

In [41]:
np_array== 3 #shows 3rd value (3) is TRUE

array([False, False,  True, False, False])

In [42]:
np_array>3 #values >3 TRUE

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [43]:
py_list= [1,2,3,4,5]
np_array= np.array(py_list)

In [50]:
#list
sum(py_list),max(py_list), min(py_list)

(15, 5, 1)

In [54]:
#array
np_array.sum(), np_array.max(), np_array.min(), np_array.mean(), np_array.std()
#std- standard deviation

(15, 5, 1, 3.0, 1.4142135623730951)