<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np
py_list= ["a1", "b2", "c3", "d4", "e5", "f6", "g7"]
#index 0, 1st position a1 and subsequently
np_array= np.array(py_list)
#pick one
x= py_list #OR
x= np_array

In [3]:
x[0]

'a1'

In [13]:
py_list[0]

'a1'

In [14]:
np_array[0]

'a1'

In [4]:
x[-1]

'g7'

In [6]:
x[0:3] #index 0-2, 3-0= 3 elements

array(['a1', 'b2', 'c3'], dtype='<U2')

In [7]:
x[1:6] #6-1= 5 elements, index 1-5

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U2')

In [8]:
x[1:6:2] #index 1-5 in 2 steps

array(['b2', 'd4', 'f6'], dtype='<U2')

In [9]:
x[5:] #index 5 to the end

array(['f6', 'g7'], dtype='<U2')

In [10]:
x[:5] #5 elements from index 0, same as [0:5]

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U2')

In [11]:
x[5:2:-1] #index 5 to 3 in reverse because -1 (5-2= 3 elements)

array(['f6', 'e5', 'd4'], dtype='<U2')

In [12]:
x[::-1] #reverse list

array(['g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'], dtype='<U2')

## 1.2 Arrays only | Subsetting by masking

In [17]:
#subsetting by masking only works with numpy arrays
np_array= np.array([1,2,3,4,5,6,7,8,9,10])
my_mask= np_array>3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [18]:
#ask numpy to show TRUE values of the mask only
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [19]:
np_array[~(np_array>3)]  # ~ means NOT

array([1, 2, 3])

In [20]:
#combining masks AnB
np_array[(np_array>3) & (np_array<8)]

array([4, 5, 6, 7])

In [22]:
#combine one mask OR another mask AuB
np_array[(np_array<3) | (np_array>8)] # | means OR

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [25]:
py_list_2d= ([1, "A"], [2, "B"], [3, "C"], [4, "D"])
np_array_2d= np.array(py_list_2d)
py_list_2d[3] #what is index 3 AKA 4th position

[4, 'D']

In [32]:
np_array_2d[3] #using py_list wont display 'array', using np_array does

array(['4', 'D'], dtype='<U11')

In [27]:
py_list_2d[3][0] #first element at index 3 AKA 4th position

4

In [28]:
np_array_2d[3, 0] #same as above but array only uses single pair of [] to run 2 different commands

'4'

In [29]:
py_list_2d[:3] #first 3 elements from index 0

([1, 'A'], [2, 'B'], [3, 'C'])

In [31]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U11')

In [33]:
py_list_2d[:3][0] #only gives 1st element from index 0

[1, 'A']

In [34]:
np_array_2d[:3, 0] #gives first 3 elements from index 0

array(['1', '2', '3'], dtype='<U11')

In [35]:
py_list_2d[3:6][0] #only gives 1st element from index 3

[4, 'D']

In [36]:
np_array_2d[3:6, 0] #gives first 3 elements from index 3

array(['4'], dtype='<U11')

In [37]:
np_array_2d[:, 0] # : gives everything

array(['1', '2', '3', '4'], dtype='<U11')

## 1.4 Growing lists

In [38]:
x=[1,2]*5 #display 1,2 for 5 times
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [39]:
x=[1]
x=x+[2]
x=x+[3]
x=x+[4]
x
#add 1 element at a time 
#x=x+

[1, 2, 3, 4]

In [40]:
x=[1]
x+=[2]
x+=[3]
x+=[4]
x
#x+=

[1, 2, 3, 4]

In [41]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x
#append runs faster than the previous 2 versions

[1, 2, 3, 4]

In [42]:
x=[1,2,3]
x+=[4,5,6]
x
#incorporates x= and x+=

[1, 2, 3, 4, 5, 6]

In [43]:
x=[1,2,3]
x.extend([4,5,6])
x

[1, 2, 3, 4, 5, 6]

In [44]:
x=[1,2,3]
x.append([4,5,6]) #displays [] on the numbers added
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [45]:
a=(1,2,3) #tuple uses () cannot be changed after creation
print(a[0]) #access data

1


In [46]:
#cannot change data (error message will appear)
a[0]=-1
a[0]+=[10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [2]:
#do not copy lists as below
x=[1,2,3]
y=x #DONT DO THIS
z=x #DONT DO THIS
#python will show x y z have the same identity

In [3]:
#use x.copy() instead to work
x=[1,2,3]
y=x.copy()
z=x.copy()

In [4]:
y

[1, 2, 3]

In [5]:
z

[1, 2, 3]